---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex
resources:
  - ../../../base/plex/resources/
  - ./ingresses.yaml
images:
  - name: lscr.io/linuxserver/plex
    newTag: 1.42.1  # {"$imagepolicy": "flux-system:plex:tag"}
