---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/github-arc/
patches:
  - target:
      kind: OCIRepository
    patch: |-
      - op: replace
        path: /spec/ref/semver
        value: ">=0.13.0 <0.14.0"
