---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mealie
resources:
  - ../../../base/mealie/resources/
  - ./ingresses.yaml
images:
  - name: ghcr.io/mealie-recipes/mealie
    newTag: v3.1.2  # {"$imagepolicy": "flux-system:mealie:tag"}
