---
name: Platform Layer CI

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/platform-layer*"
      - ".requirements/**"
      - "platform-layer/**"

jobs:
  lint:
    runs-on: homeops-arc-runners

    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          terraform_version: '1.4.4'
          terraform_wrapper: false

      - name: Run linters
        run: task platform-layer:lint
