---
name: Software Layer CI

on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/software-layer*"
      - ".requirements/**"
      - "software-layer/**"

jobs:
  lint:
    runs-on: homeops-arc-runners

    steps:
      - name: Checkout the repo at current context
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Run linters
        run: task software-layer:lint
